## Table create ##
##CREATE TABLE MP_PRD_TEMP (FILE_NAME VARCHAR(50), TRANS_STATUS VARCHAR(20), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50), PDF_DATA JSON, PDF_UPDATE_STATUS VARCHAR(20), STELLA_DATA JSON, STELLA_UPDATE_STATUS VARCHAR(20), IMAGES_DATA JSON, IMAGES_UPDATE_STATUS VARCHAR(20), PRIMARY KEY (FILE_NAME, UPC_ID, OP_DIV));

CREATE TABLE MP_PDF_MASTER (FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50), PDF_DATA JSON, PRIMARY KEY (UPC_ID, OP_DIV));

CREATE TABLE MP_STELLA_MASTER (FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50), STELLA_DATA JSON, PRIMARY KEY (UPC_ID, OP_DIV));

CREATE TABLE MP_IMAGES_MASTER (FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50), IMAGE_DATA JSON, PRIMARY KEY (UPC_ID, OP_DIV));

CREATE TABLE MP_UPC_MASTER (UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50), DEPT VARCHAR(20), VENDOR VARCHAR(50), PID VARCHAR(20), NRF_COLOR_CODE VARCHAR(10), TAX_CODE VARCHAR(50), NRF_SIZE_CODE VARCHAR(10), MSRP VARCHAR(20), OFFER_ID VARCHAR(50), MAIN_IMG_FLAG BOOLEAN, BUYER_APPROVED_FLAG BOOLEAN, PRIMARY KEY (UPC_ID, OP_DIV));

CREATE TABLE MP_OFFER_AUDIT (CREATE_TS TIMESTAMP, FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), OFFER_ID VARCHAR(50), OFFER_ID_STATUS VARCHAR(20), ERROR_DESC VARCHAR(50));

CREATE TABLE MP_CREATE_RESP_AUDIT (CREATE_TS TIMESTAMP, UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_SKU VARCHAR(50), PID VARCHAR(20), NRF_COLOR_CODE VARCHAR(10), NRF_SIZE_CODE VARCHAR(10), MSRP VARCHAR(20), TAX_CODE VARCHAR(50));

CREATE TABLE MP_FACET_MASTER (FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50),DEPT VARCHAR(20), VENDOR VARCHAR(50), PID VARCHAR(20), NRF_COLOR_CODE VARCHAR(10),FACET_DATA JSON, PRIMARY KEY (UPC_ID, OP_DIV));

CREATE TABLE MP_PDF_AUDIT (CREATE_TS TIMESTAMP, OPERATION VARCHAR(20), STATUS VARCHAR(20), ERROR_DESC VARCHAR(1000), FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50),PDF_DATA JSON);

CREATE TABLE MP_STELLA_AUDIT (CREATE_TS TIMESTAMP, OPERATION VARCHAR(20), STATUS VARCHAR(20), ERROR_DESC VARCHAR(1000), FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50), STELLA_DATA JSON);

CREATE TABLE MP_IMAGES_AUDIT (CREATE_TS TIMESTAMP, OPERATION VARCHAR(20), STATUS VARCHAR(20), ERROR_DESC VARCHAR(1000), FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50),IMAGE_DATA JSON);

CREATE TABLE MP_FACET_AUDIT (CREATE_TS TIMESTAMP, OPERATION VARCHAR(20), STATUS VARCHAR(20), ERROR_DESC VARCHAR(1000), FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50),DEPT VARCHAR(20), VENDOR VARCHAR(50), PID VARCHAR(20), NRF_COLOR_CODE VARCHAR(10),FACET_DATA JSON);

CREATE TABLE MP_PDF_TEMP (OPERATION VARCHAR(20), FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50), PDF_DATA JSON, PRIMARY KEY (UPC_ID, OP_DIV, FILE_NAME));

CREATE TABLE MP_STELLA_TEMP (OPERATION VARCHAR(20), FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50), STELLA_DATA JSON, PRIMARY KEY (UPC_ID, OP_DIV, FILE_NAME));

CREATE TABLE MP_IMAGES_TEMP (OPERATION VARCHAR(20), FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50), IMAGE_DATA JSON, PRIMARY KEY (UPC_ID, OP_DIV, FILE_NAME));

CREATE TABLE MP_FACET_TEMP (OPERATION VARCHAR(20), FILE_NAME VARCHAR(50), UPC_ID VARCHAR(20), OP_DIV VARCHAR(10), PRODUCT_TYPE VARCHAR(50), DEPT VARCHAR(20), VENDOR VARCHAR(50), PID VARCHAR(20), NRF_COLOR_CODE VARCHAR(10), FACET_DATA JSON, PRIMARY KEY (UPC_ID, OP_DIV, FILE_NAME));